### ISSUE TITLE
NFT Key contract minting and storage issue

### ISSUE THREAD

**Issue by mikedotexe** [near/near-multichain-xchain-relayer#14]
I was wanting to try this out and deployed one to a subaccount.

>Predecessor has not registered for storage

<img width="1389" alt="Screenshot 2024-04-22 at 4 52 05 PM" src="https://github.com/near/multichain-gas-station-contract/assets/1042667/8a2d5a99-1ae7-4850-85cb-b7c89ac62718">

Steps:

```sh
cd nft_key
cargo build --target wasm32-unknown-unknown --release
cp ../target/wasm32-unknown-unknown/release/nft_key.wasm ../res
near deploy mpc.x.mike.testnet --wasmFile ../res/nft_key.wasm --initFunction new --initArgs '{"signer_contract_id": "sign.x.mike.testnet"}'
near call mpc.x.mike.testnet mint '{}' --accountId mpc.x.mike.testnet
```

It seems that the initial call to `deposit_to_storage_account` hasn't been made, so when `storage_accounting` is called, it's throwing this.

Maybe I'm doing something wrong

**Comment by encody** [comment]
You need to make a call to `storage_deposit` as well (conforming to the [storage management standard](https://nomicon.io/Standards/StorageManagement)).

**Comment by mikedotexe** [comment]
Please add to the README

**Comment by encody** [comment]
It is in the readme: https://github.com/near/multichain-gas-station-contract/tree/master/nft_key#creating-new-key-tokens
