### ISSUE TITLE
Add `path` so users can control multiple foreign accounts

### ISSUE THREAD

**Issue by gagdiez** [near/near-multichain-xchain-relayer#2]
One of the main features of the `Signer Contract` is that it allows to request signatures for different foreign accounts by changing the `path`:

https://github.com/near/mpc-recovery/blob/e729a9a74038d3726e6756cc3bc565856eeadb21/contract/src/lib.rs#L298

For example, the account `test.near` can control:

- `path`: `ethereum-1`, `foreign address`: 0x123....
- `path`: `ethereum-2`, `foreign address`: 0x456...

The current implementation of the `multichain-gas-station-contract` always uses the same path:

https://github.com/near/multichain-gas-station-contract/blob/6f5c7e3f35d6834059450df32b7673642b595213/gas_station/src/lib.rs#L211-L212

While this is not a problem, it constraints that a NEAR account can only control one foreign account. By adding a `path` parameter, users could take full advantage of the `signer contract` and control multiple foreign account from a single NEAR account.

**Comment by encody** [comment]
Will be sidestepped/fixed by #7

**Comment by encody** [comment]
Closed by #7
